"""
Build lang/es.js and lang/zh.js from lang/strings.txt.

strings.txt holds one block per interface string: the English key, the
Spanish, the Chinese, each on its own line, blocks separated by a blank
line. Lines starting with # are comments. {0}, {1}, ... are the numbers the
page puts back; every translation must carry the same slots as its key.

    python webapp/lang/build.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
LANGS = ("es", "zh")
SEPARATOR = {"es": "; ", "zh": "；"}


def read(path: Path) -> list[tuple[str, ...]]:
    blocks, current = [], []
    for line in path.read_text(encoding="utf-8").splitlines() + [""]:
        if line.startswith("#"):
            continue
        if line.strip():
            current.append(line.rstrip("\n"))
            continue
        if current:
            blocks.append(tuple(current))
            current = []
    return blocks


def slots(text: str) -> list[str]:
    return sorted(re.findall(r"\{\d+\}", text))


def main() -> int:
    blocks = read(HERE / "strings.txt")
    problems = []
    tables = {lang: {} for lang in LANGS}
    for block in blocks:
        if len(block) != 1 + len(LANGS):
            problems.append(f"block needs {1 + len(LANGS)} lines: {block}")
            continue
        key = block[0]
        for lang, text in zip(LANGS, block[1:]):
            if slots(text) != slots(key):
                problems.append(f"{lang}: slots differ in {key!r} -> {text!r}")
            if key in tables[lang]:
                problems.append(f"duplicate key {key!r}")
            tables[lang][key] = text
    for lang in LANGS:
        tables[lang]["; "] = SEPARATOR[lang]
        body = json.dumps(tables[lang], ensure_ascii=False, indent=1, sort_keys=True)
        (HERE / f"{lang}.js").write_text(
            "/* Generated by lang/build.py from lang/strings.txt. Edit that file. */\n"
            f"I18N.add(\"{lang}\", {body});\n", encoding="utf-8")
    print(f"{len(blocks)} strings, {len(LANGS)} languages")
    for p in problems:
        print("  " + p)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
